#!/usr/bin/env bash

mkdir -p /tmp/s3-bash-files
cd /tmp/s3-bash-files
touch a.txt b.txt c.txt d.txt && echo "abc" > a.txt && echo "abc" > b.txt && echo "abc" > c.txt && echo "abc" > d.txt

# check if an argument is provided
if [ -z "$1" ]; then
    echo "There needs to be a bucket name"
    exit 1
fi

aws s3 cp /tmp/s3-bash-files s3://"$1" --recursive
if [ $? -ne 0 ]; then
    echo "Failed to upload files to S3 bucket $1"
    exit 1
fi
echo "Files successfully uploaded to S3 bucket $1"
# clean up
rm -rf /tmp/s3-bash-files
# exit with success
exit 0
# Note: This script uploads files to an S3 bucket. Make sure you have the AWS CLI configured with the necessary permissions.
# Usage: ./put-object.sh <bucket-name>
# Example: ./put-object.sh my-bucket-name