tasks:
  setup:
    name: Setup AWS CLI
    command: |
      export AWS_CLI_AUTO_PROMPT=on-partial
      cd /workspaces
      echo "Installing AWS CLI..."
      curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd /workspaces/aws-andrew-course
    triggeredBy:
      - postDevcontainerStart
